language: node_js
node_js:
  - "13"
dist: bionic
addons:
  apt:
    packages:
    - libsecret-1-dev
services:
  - xvfb
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
